# Generated by Django 4.2.6 on 2024-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('leader_name', models.CharField(max_length=50)),
                ('group_email', models.EmailField(max_length=254)),
                ('round1', models.BooleanField(default=False)),
                ('round2', models.BooleanField(default=False)),
                ('round3', models.BooleanField(default=False)),
                ('round4', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
    ]
